package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Contract struct{ID int64 `json:"id"`;Name string `json:"name"`;URL string `json:"url"`;Method string `json:"method"`;ExpectedStatus int `json:"expected_status"`;ExpectedBodyContains string `json:"expected_body_contains"`;LastStatus string `json:"last_status"`;LastRun *string `json:"last_run"`;CreatedAt time.Time `json:"created_at"`}
type Result struct{ID int64 `json:"id"`;ContractID int64 `json:"contract_id"`;Passed bool `json:"passed"`;ActualStatus int `json:"actual_status"`;Error string `json:"error"`;DurationMs int64 `json:"duration_ms"`;RanAt time.Time `json:"ran_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"assay2.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS contracts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,url TEXT NOT NULL,method TEXT DEFAULT 'GET',expected_status INTEGER DEFAULT 200,expected_body_contains TEXT DEFAULT '',last_status TEXT DEFAULT '',last_run TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,contract_id INTEGER NOT NULL,passed INTEGER NOT NULL,actual_status INTEGER DEFAULT 0,error TEXT DEFAULT '',duration_ms INTEGER DEFAULT 0,ran_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Create(c *Contract)error{res,err:=db.Exec(`INSERT INTO contracts(name,url,method,expected_status,expected_body_contains)VALUES(?,?,?,?,?)`,c.Name,c.URL,c.Method,c.ExpectedStatus,c.ExpectedBodyContains);if err!=nil{return err};c.ID,_=res.LastInsertId();return nil}
func(db *DB)List()([]Contract,error){rows,_:=db.Query(`SELECT id,name,url,method,expected_status,expected_body_contains,last_status,last_run,created_at FROM contracts ORDER BY name`);defer rows.Close();var out[]Contract;for rows.Next(){var c Contract;rows.Scan(&c.ID,&c.Name,&c.URL,&c.Method,&c.ExpectedStatus,&c.ExpectedBodyContains,&c.LastStatus,&c.LastRun,&c.CreatedAt);out=append(out,c)};return out,nil}
func(db *DB)RecordResult(res *Result){p:=0;if res.Passed{p=1};status:="pass";if !res.Passed{status="fail"};db.Exec(`INSERT INTO results(contract_id,passed,actual_status,error,duration_ms)VALUES(?,?,?,?,?)`,res.ContractID,p,res.ActualStatus,res.Error,res.DurationMs);db.Exec(`UPDATE contracts SET last_status=?,last_run=CURRENT_TIMESTAMP WHERE id=?`,status,res.ContractID)}
func(db *DB)ListResults(contractID int64)([]Result,error){rows,_:=db.Query(`SELECT id,contract_id,passed,actual_status,error,duration_ms,ran_at FROM results WHERE contract_id=? ORDER BY ran_at DESC LIMIT 50`,contractID);defer rows.Close();var out[]Result;for rows.Next(){var res Result;var p int;rows.Scan(&res.ID,&res.ContractID,&p,&res.ActualStatus,&res.Error,&res.DurationMs,&res.RanAt);res.Passed=p==1;out=append(out,res)};return out,nil}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM results WHERE contract_id=?`,id);db.Exec(`DELETE FROM contracts WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var total,failing int;db.QueryRow(`SELECT COUNT(*) FROM contracts`).Scan(&total);db.QueryRow(`SELECT COUNT(*) FROM contracts WHERE last_status='fail'`).Scan(&failing);return map[string]interface{}{"contracts":total,"failing":failing},nil}
